### ISSUE TITLE
Can't run Jekyllized / gulp. Missing Dependencies

### ISSUE THREAD

**Issue by karltaylor** [sondr3/generator-jekyllized#103]
After running yo jekyllized and running npm install & bower install I am left with the following Warnings & problems.

```
I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global pangyp@2.3.2 should be installed with -g

> bufferutil@1.2.1 install /Users/karl/test/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/karl/test/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> phantomjs@1.9.18 install /Users/karl/test/node_modules/phantomjs
> node install.js

Download already available at /var/folders/xv/wtyq8qqd3q55yjq5yg6ytd_c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/karl/test/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/xv/wtyq8qqd3q55yjq5yg6ytd_c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1446563578190/
phantomjs-1.9.8-macosx -> /Users/karl/test/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/karl/test/node_modules/phantomjs/lib/phantom/bin/phantomjs

> node-sass@2.1.1 install /Users/karl/test/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.2/binding.node

> node-sass@2.1.1 postinstall /Users/karl/test/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/karl/test/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
Build failed

> optipng-bin@3.0.2 postinstall /Users/karl/test/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@3.0.5 postinstall /Users/karl/test/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@3.0.1 postinstall /Users/karl/test/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully
```

Then after running all that I threw in gulp just to see what would happen and I got

```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/karl/test/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/karl/test/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/karl/test/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:435:26)
```

Any ideas on a fix?

**Comment by karltaylor** [comment]
Also did a `npm rebuild node-sass` and it gave me this so It must be this `node-gyp` thing?

````
> node-sass@2.1.1 install /Users/karl/test/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /Users/karl/test/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/karl/test/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
Build failed
node-sass@2.1.1 /Users/karl/test/node_modules/node-sass
```

**Comment by karltaylor** [comment]
Took me a while but running 

```
npm uninstall --save-dev gulp-sass

npm install --save-dev gulp-sass@2

```

and then 

```
bundle
```

Did the trick. However there was then a few errors within jekyll it's self which I got around - 

- `You appear to have pagination turned on`
- `pages in subfolders must be relative to the site source directory, not the parent directory.`
- `You appear to have pagination turned on, but you haven't included the "jekyll-paginate" gem`

Then once I got rid of everything in `# Permalink structure and pagination options` in the `_config.yml` file. It gave me this - 

`liquid Exception: Liquid syntax error: Unknown tag 'gist' in /Users/karl/test/src/_drafts/2014-03-01-example-content.md/#excerpt`

Which I removed.

So I finally got it working but it's a bit buggy. I assume this might be due to the latest node update.

**Comment by sondr3** [comment]
It gives you this error in the first log, so it's probably related to that.

```
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.2/binding.node
```

Not really sure what the problem could be because it seems like a 404 or something. What versions of Node/NPM and OS X are you running?

**Comment by sondr3** [comment]
Oh, didn't see the last one. Yes, probably, and I haven't tested it for the final release of Jekyll 3 so there's probably some errors here and there. I'll fix it later today if I have the time.

**Comment by karltaylor** [comment]
node -v
v4.2.1
npm -v
3.3.10

**Comment by sondr3** [comment]
Yeah, I really don't know what could cause that. You're probably better off asking the developers of node-sass.

**Comment by sondr3** [comment]
Quick question, were you installing from NPM or did you download the beta?

**Comment by karltaylor** [comment]
Do you mean jekyllized? I installed it via npm!

**Comment by karltaylor** [comment]
ah shit I

**Comment by sondr3** [comment]
Yeah, the error is probably from the version of node-sass on NPM is very old. About eight months, I haven't pushed a new version yet because I'm waiting for Gulp 4.0 to be released :)

**Comment by ginfuru** [comment]
#### Having the same issues:
Though I got it working by following @karltaylor [work around] (https://github.com/sondr3/generator-jekyllized/issues/103#issuecomment-153398660) for `node-sass`
But to kept everything happy by including `jekyll-paginate` inside of my `Gemfile` followed by running `bundle install` and including the plugin inside of my `_config.yml` 
```yaml
gems:
  - jekyll-paginate
```
And in `_config.yml` I commented out/removed: `relative_permalinks: true`
```yaml
# Permalink structure and pagination options
#relative_permalinks: true
permalink: pretty
paginate: 3
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'
```
which as everything working as expected.  

Figured I'd chime in **_just in case_** someone else wanted to keep pagination while using the [Lanyon theme](https://github.com/poole/lanyon) or with their own theme.

Here is the full config:
```yaml
# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Rainy Day Media
description: officially breaking up with WordPress 
tagline: make it rain bitches
url: localhost:4000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: Ed
  email: ed@rainydaymedia.net
  bio: I'm an avid front-end web developer and closet logo designer
  twitter: ginfuru

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

gems:
  - jekyll-paginate
# Permalink structure and pagination options
#relative_permalinks: true
permalink: pretty
paginate: 3
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true
```

**Comment by sondr3** [comment]
This is all fixed in the beta version, it's just both node-sass and Jekyll have had major updates :)

**Comment by ginfuru** [comment]
@sondr3 Super!

**Comment by sondr3** [comment]
Yeah, I'm pretty much just waiting for Gulp 4.0 to be released and then I'll push a new version to NPM.

**Comment by ginfuru** [comment]
@sondr3 Yeah I can respect that :+1:
