### ISSUE TITLE
SyntaxError after running gulp

### ISSUE THREAD

**Issue by miukimiu** [sondr3/generator-jekyllized#104]
I get this error after I run gulp
```
Requiring external module babel-core/register
/Users/miukimiu/Repos/testing/gulpfile.babel.js:3
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at loader (/Users/miukimiu/Repos/testing/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/miukimiu/Repos/testing/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js:32:3)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:150:63)
```

When i run gulp - v

```
Requiring external module babel-core/register
CLI version 0.4.0
Local version 4.0.0-alpha.1
```
bundler -v
```
Bundler version 1.10.6
```
node -v 
```
v5.1.0
```

ruby -v
```
ruby 2.2.3p173 
```

yo --version
```
1.5.0
```

Can you help me with this issue?

**Comment by humantorch** [comment]
Was just coming here to post this *exact* same issue. #serendipity

**Comment by sondr3** [comment]
Yeah, I think the newest version of Babel broke the current setup and I didn't catch that. I'll push an update when I get home later today and let you know here how to fix it.

You could try to make a `.babelrc` file with 

```
{
  "preset": ['preset-2015']
}
```

I'm on mobile right now though so I can't double check if I wrote that correct 😅

**Comment by humantorch** [comment]
Thanks for the quick reply! First off, I've not worked with Babel before so my Babel-fu is weaksauce.

That said, I added a `.babelrc` file to my project with the content you specified, and while I'm still getting an error, I'm getting a _different_ error now.

```
➜  yojek  gulp
[17:25:54] Requiring external module babel-core/register
/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/logger.js:43
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/scott/Documents/Projects/WebServer/yojek/gulpfile.babel.js: Unknown option: /Users/scott/Documents/Projects/WebServer/yojek/.babelrc.preset
    at Logger.error (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:18)
    at OptionManager.addConfig (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/options/option-manager.js:223:10)
    at OptionManager.findConfigs (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/options/option-manager.js:366:16)
    at OptionManager.init (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/options/option-manager.js:410:12)
    at File.initOptions (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-core/lib/api/node.js:118:10)
    at compile (/Users/scott/Documents/Projects/WebServer/yojek/node_modules/babel-register/lib/node.js:103:20)
```

**Comment by sondr3** [comment]
Yeah, it was supposed to be 

```
{
  "presets": ["es2015"]
}
```

That should work :)

**Comment by humantorch** [comment]
Hrm. This seems to have sorted the initial issue, but an entirely different error is getting thrown now.

```
[17:40:44] Requiring external module babel-core/register
[17:40:45] Using gulpfile ~/Documents/Projects/WebServer/yojek/gulpfile.babel.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

This looks to be more of an issue with gulp itself. @miukimiu is the `presets` fix above working for you? That'd narrow down to see if it's a problem with my local gulp setup or not.

**Comment by miukimiu** [comment]
@humantorch this fix is working for me.

I've just created a `.babelrc` in the project folder and placed there the following code:
```
{
  "presets": ["es2015"]
}
```
So, finally the project is running! :+1: 

Maybe you need `node 5.0.1`

**Comment by sondr3** [comment]
No, it's an issue with the newest version of Babel. Without that file and the preset it does nothing and therefore breaks Gulp since it uses ES2015 features. Kinda stupid if you ask me but hey. I'll push another beta version later today with a fix.

**Comment by sondr3** [comment]
I've now published a new version of Jekyllized that fixes this problem! Thank you for reporting this error :)

**Comment by humantorch** [comment]
Works a treat now, thanks!
