### ISSUE TITLE
Error Generating Project

### ISSUE THREAD

**Issue by CGTS** [sondr3/generator-jekyllized#122]
I just ran 'Yo Jekyllized' after installing 'npm install generator-jekyllized@next -g'. Yeoman runs through all the project questions and then spits out the following error without building the site:

```
Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\name\AppData\Roaming\npm\node_modules\generator-jekyllized\generators\gulp\index.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Any ideas on how to fix this?

**Comment by CGTS** [comment]
Duplicate of #121. Closing

**Comment by sondr3** [comment]
Keep a watch on the other thread, I'll fix this as soon as I'm home.
