### ISSUE TITLE
Error when running gulp.

### ISSUE THREAD

**Issue by ghost** [sondr3/generator-jekyllized#142]
Hi,

I am seeing this when running gulp:

_[15:54:15] Using gulpfile ~/Dropbox/Web Projects/gtgoot/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
gulpInst.start.apply(gulpInst, toRun);
^
TypeError: Cannot read property 'apply' of undefined
at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
at Module.runMain (module.js:577:11)
at run (bootstrap_node.js:352:7)
at startup (bootstrap_node.js:144:9)
at bootstrap_node.js:467:3_

I've read that this can be to do with the gulp-cli version no. but I believe my version is up to date?

_[15:53:51] CLI version 3.9.1
[15:53:51] Local version 4.0.0-alpha.2_

Any idea how I can solve this please?

**Comment by sondr3** [comment]
Not really sure, I'll take a look once I come back from vacation in a week! Hope you'll figure it out in the meantime.

**Comment by emilianos** [comment]
im getting the same issue:

```
[16:44:21] Using gulpfile ~/Documents/_dev/jekyllized-0712/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by emilianos** [comment]
ok, got it working
just needed to install the latest gulp version:

`npm install gulp-cli -g`

**Comment by sondr3** [comment]
Yeah, that would probably explain why :)
