### ISSUE TITLE
Assertion error when running gulp

### ISSUE THREAD

**Issue by activeflush** [sondr3/generator-jekyllized#147]
Hi there, 
This maybe a simple question but I did a new install of this and when I try to run gulp the below appears:

`assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Task never defined: site:tmp
    at getFunction (/Users/mw/Documents/jekyll/fd1/05-jekyllized/node_modules/undertaker/lib/helpers/normalizeArgs.js:15:5)
    at arrayMap (/Users/mw/Documents/jekyll/fd1/05-jekyllized/node_modules/lodash.map/index.js:140:21)
    at map (/Users/mw/Documents/jekyll/fd1/05-jekyllized/node_modules/lodash.map/index.js:1836:10)
    at normalizeArgs (/Users/mw/Documents/jekyll/fd1/05-jekyllized/node_modules/undertaker/lib/helpers/normalizeArgs.js:19:10)
    at Gulp.series (/Users/mw/Documents/jekyll/fd1/05-jekyllized/node_modules/undertaker/lib/series.js:13:14)
    at Object.<anonymous> (/Users/mw/Documents/jekyll/fd1/05-jekyllized/gulpfile.js:13:30)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at execute (/Users/mw/.npm-packages/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:35:18)
    at Liftoff.handleArguments (/Users/mw/.npm-packages/lib/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/Users/mw/.npm-packages/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)
`

Just not quite sure what to do here. Thanks!

**Comment by sondr3** [comment]
I know where the error is, crap, I completely overlooked something when fixing something yesterday. I'm at work right now but I'll push a fix as soon as I get home.

**Comment by activeflush** [comment]
awesome, thanks for the quick update :)

**Comment by sondr3** [comment]
And done! You can update the generator and either reinstall it or just update it with `yo jekyllized:update` and you should be fine again.
