### ISSUE TITLE
Errors while running yo jekyllized and gulp

### ISSUE THREAD

**Issue by evanderkoogh** [sondr3/generator-jekyllized#150]
I am trying to use jekyllized as it looks absolutely amazing, but I am running into a few issues running both `yo jekyllized` and `gulp`.

The `yo jekyllized` command has the following errors in it: 
```
Errno::EACCES: Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15
...
...
An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.
```

When I then try to run a `gulp` the following error happens:

```
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:356:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-seo-tag' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `each'
```

Which is probably unsurprising to someone who understands Ruby and gems and bundle etc.. (I do not)

Versions of software:

OSX: 10.11.6 (15G31)
```
Nuggan:bitgenics.io evanderkoogh$ rbenv version
2.3.0 (set by /Users/evanderkoogh/.rbenv/version)
Nuggan:bitgenics.io evanderkoogh$ gem -v
2.6.6
Nuggan:bitgenics.io evanderkoogh$ bundle -v
Bundler version 1.12.5
Nuggan:bitgenics.io evanderkoogh$ yo --version
1.8.5
Nuggan:bitgenics.io evanderkoogh$ nvm version
v6.5.0
Nuggan:bitgenics.io evanderkoogh$ gulp -v
[13:48:56] CLI version 1.2.2
[13:48:56] Local version 4.0.0-alpha.2
Nuggan:bitgenics.io evanderkoogh$ 
```

I have tried to run a couple things as root, manually install those gems. But nothing really works.
Any help would be greatly appreciated!

Full output of `yo jekillized`: 

```
Creating files and running npm install and bundle install.

   create package.json
   create .editorconfig
   create .gitattributes
   create .gitignore
   create README.md
   create gulpfile.js
   create gulp/tasks/assets.js
   create gulp/tasks/clean.js
   create gulp/tasks/copy.js
   create gulp/tasks/fonts.js
   create gulp/tasks/html.js
   create gulp/tasks/images.js
   create gulp/tasks/inject.js
   create gulp/tasks/uploading.js
   create aws-credentials.json
   create gulp/tasks/build.js
   create Gemfile
   create _config.yml
   create _config.build.yml
   create src/humans.txt
   create src/_drafts/2014-03-01-example-content.md
   create src/_includes/footer.html
   create src/_includes/head.html
   create src/_includes/header.html
   create src/_includes/icon-github.html
   create src/_includes/icon-github.svg
   create src/_includes/icon-twitter.html
   create src/_includes/icon-twitter.svg
   create src/_layouts/default.html
   create src/_layouts/page.html
   create src/_layouts/post.html
   create src/_posts/2014-03-03-welcome-to-jekyll.md
   create src/404.html
   create src/about.md
   create src/assets/favicon.ico
   create src/assets/images/touch/apple-touch-icon-144-precomposed.png
   create src/assets/javascript/main.js
   create src/assets/javascript/vendor.js
   create src/assets/scss/base.scss
   create src/assets/scss/layout.scss
   create src/assets/scss/main.scss
   create src/assets/scss/style.scss
   create src/assets/scss/syntax-highlighting.scss
   create src/crossdomain.xml
   create src/index.html
   create src/robots.txt
⸨      ░░░░░░░░░░░░⸩ ⠸ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/babel-plugin-transform-es2015-unicode-regex
Fetching version metadata from http://rubygems.org/⸨      ░░░░░░░░░░░░⸩ ⠼ fetchMetadata: verb afterAdd /Users/evanderkoogh/.npm/babel-plugin-transform-es2015-modules-commonjs/6.14.0/package/package.json w⸨      ░░░░░░░░░░░░⸩ ⠹ fetchMetadata: verb afterAdd /Users/evanderkoogh/.npm/babel-helper-function-name/6.8.0/package/package.json written
Fetching dependency metadata from http://rubygems.org/ry uri https://registry.npmjs.org/shebang-regex
⸨      ░░░░░░░░░░░░⸩ ⠋ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/ua-parser-js
Using addressable 2.4.0fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/ua-parser-js
Using colorator 1.1.0
Using multipart-post 2.0.0
Installing ffi 1.9.14 with native extensionsapToRegistry uri https://registry.npmjs.org/readdirp
⸨      ░░░░░░░░░░░░⸩ ⠙ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/readdirp
Errno::EACCES: Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15
Using forwardable-extended 2.6.0
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.12.0
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using jekyll-feed 0.6.0
Using jekyll-paginate 1.1.0
Installing redcarpet 3.3.4 with native extensionsegistry uri https://registry.npmjs.org/readdirp

Using bundler 1.12.5
Using jekyll-sitemap 0.11.0
Using faraday 0.9.2
An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> fsevents@1.0.14 install /Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> node-sass@3.9.0 install /Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.0/darwin-x64-48_binding.node
Binary downloaded and installed at /Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/node-sass/vendor/darwin-x64-48/binding.node

> node-sass@3.9.0 postinstall /Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/node-sass
> node scripts/build.js

"/Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/node-sass/vendor/darwin-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.

> gifsicle@3.0.4 postinstall /Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.1.0 postinstall /Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.2 postinstall /Users/evanderkoogh/Dropbox/Bitgenics/PR/website/bitgenics.io/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
```

**Comment by evanderkoogh** [comment]
Ok.. I was messing around with it some more and fixed it:

I ran the `yo jekyllized` command with the errors. Then I ran `sudo gem install ffi -v '1.9.14'`, `sudo gem install redcarpet -n/usr/local/bin` & `bundle install`.

Not the best way of solving it I am sure, but we'll cross that bridge when we get there.

**Comment by sondr3** [comment]
No, it has something to do with your installation of Ruby. You're running the default version included in El Capitan? I highly recommend installing ruby via either homebrew or rvm etc :)

**Comment by evanderkoogh** [comment]
No, I am running the 2.3.0 installed via rbenv. Oh wait, no that might not have been the case. Let me dig a bit deeper.

**Comment by sondr3** [comment]
```
Errno::EACCES: Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15
...
...
An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.
```

Here it looks like you're using ruby 2.0.0 and not 2.3.0. You're sure you've enabled it correctly globally?

**Comment by evanderkoogh** [comment]
Yup.. tracked it down. I had enabled it globally, but there was a problem with the path. I have submitted a pull request with a link that explains the installation process on El Capitan.

**Comment by evanderkoogh** [comment]
Thanks for the plugin, the help, and pointers. This can be closed.
