### ISSUE TITLE
Error when using gulp cannot get

### ISSUE THREAD

**Issue by papaponmx** [sondr3/generator-jekyllized#155]
When running gulp, I get the following error on the local host

`Cannot GET /`

Checking gulp, this is the message that appears

```gulp
(node:12843) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[18:25:11] Using gulpfile ~/Documents/nextrobotix.com/gulpfile.js
[18:25:11] Starting 'default'...
[18:25:11] Starting 'build'...
[18:25:11] Starting 'clean'...
[18:25:11] Starting 'clean:assets'...
[18:25:11] Starting 'clean:gzip'...
[18:25:11] Starting 'clean:dist'...
[18:25:11] Starting 'clean:site'...
[18:25:11] Finished 'clean:gzip' after 607 ms
[18:25:11] Finished 'clean:site' after 647 ms
[18:25:11] Finished 'clean:assets' after 656 ms
[18:25:11] Finished 'clean:dist' after 656 ms
[18:25:11] Finished 'clean' after 660 ms
[18:25:11] Starting 'assets'...
[18:25:11] Starting 'styles'...
[18:25:11] Starting 'scripts'...
[18:25:11] Starting 'fonts'...
[18:25:11] Starting 'images'...
[18:25:12] Finished 'fonts' after 814 ms
[18:25:14] style.css 10.38 kB
[18:25:14] index.js 57 B
[18:25:14] Finished 'styles' after 2.91 s
[18:25:14] Finished 'scripts' after 2.92 s
[18:25:15] images all files 1.55 MB
[18:25:15] Finished 'images' after 3.41 s
[18:25:15] Starting 'copy:assets'...
[18:25:15] Finished 'copy:assets' after 255 ms
[18:25:15] Finished 'assets' after 3.69 s
[18:25:15] Starting 'build:site'...
[18:25:15] Starting 'site:tmp'...
[18:25:15] Jekyll all files 26.41 kB
[18:25:16] Finished 'site:tmp' after 372 ms
[18:25:16] Starting 'inject'...
[18:25:16] Starting 'inject:head'...
[18:25:16] Starting 'inject:footer'...
[18:25:16] gulp-inject 1 files into head.html.
[18:25:16] gulp-inject 1 files into default.html.
[18:25:16] Finished 'inject:head' after 71 ms
[18:25:16] Finished 'inject:footer' after 71 ms
[18:25:16] Finished 'inject' after 73 ms
[18:25:16] Starting 'site'...
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated addressable 2.5.0, but your Gemfile requires addressable 2.4.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `map'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `setup'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/exe/jekyll:9:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
[18:25:19] Finished 'site' after 3.91 s
[18:25:19] Starting 'copy:site'...
[18:25:19] Finished 'copy:site' after 4.55 ms
[18:25:20] Finished 'build:site' after 4.38 s
[18:25:20] Starting 'html'...
[18:25:20] Finished 'html' after 100 ms
[18:25:20] Finished 'build' after 8.84 s
[18:25:20] Starting 'serve'...
[18:25:20] Finished 'serve' after 101 ms
[18:25:20] Finished 'default' after 8.95 s
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3002
    External: http://192.333.100.4:3002
 --------------------------------------
          UI: http://localhost:3003
 UI External: http://192.333.100.4:3003
 --------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: dist

```

I've checked the previews responses. Verified all the dependencies, updated the plugin and ran `sudo npm update -g generator-jekyllized` and then  `sudo yo jekyllized:update `

**Comment by sondr3** [comment]
You have some an error with your gems that Jekyll requires:

```
[18:25:16] Starting 'site'...
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated addressable 2.5.0, but your Gemfile requires addressable 2.4.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `map'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `setup'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/exe/jekyll:9:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
```

You need to clean out your gems with `bundle clean --force` and reinstall them with `bundle install`.

**Comment by papaponmx** [comment]
It works now, I used `sudo bundle update`

**Comment by sondr3** [comment]
Yeah, anything that properly updates and install your gems would fix this. I usually just nuke them from orbit and reinstall :smile:
