### ISSUE TITLE
First attempt to run default task returns error

### ISSUE THREAD

**Issue by mikhailbalin** [sondr3/generator-jekyllized#157]
Hi, 

I'm not sure what I'm seeing there, but it feels like its something with Gulp there? I've just run `gulp` after a complete new installation.

```
[10:09:44] Using gulpfile ~/Documents/Websites/jekyllized/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Installed on my Mac:
Ruby 2.4.0p0
CLI version 3.9.1
Gulp Local version 4.0.0-alpha.2
Yeoman 1.8.5
Node v6.9.4
jekyll 3.4.0

Thank you!

**Comment by mikhailbalin** [comment]
I've installed Gulp Cli one more time and it worked! The way this "under hood stuff" works it just fascinating 🙃 Thank you for generator, it's really good!
