### ISSUE TITLE
Error on gulp deploy

### ISSUE THREAD

**Issue by pdkaizer** [sondr3/generator-jekyllized#160]
I am getting the following when I do gulp deploy command: 'upload' errored after 2.58 s
[19:29:36] TypeError: Cannot read property 'length' of undefined
    at Pumpify.Duplexify._forward (/Users/peterkaizer/Personal-git-projects/peterkaizer.com/node_modules/duplexify/index.js:161:76)
    at XmlToObj.onreadable (/Users/peterkaizer/Personal-git-projects/peterkaizer.com/node_modules/duplexify/index.js:126:10)
    at emitNone (events.js:86:13)
    at XmlToObj.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at XmlToObj.Readable.push (_stream_readable.js:134:10)
    at XmlToObj.Transform.push (_stream_transform.js:128:32)
    at /Users/peterkaizer/Personal-git-projects/peterkaizer.com/node_modules/xml-objects/index.js:24:10
    at Parser.<anonymous> (/Users/peterkaizer/Personal-git-projects/peterkaizer.com/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/Users/peterkaizer/Personal-git-projects/peterkaizer.com/node_modules/xml2js/lib/xml2js.js:444:26)
    at emit (/Users/peterkaizer/Personal-git-projects/peterkaizer.com/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/Users/peterkaizer/Personal-git-projects/peterkaizer.com/node_modules/sax/lib/sax.js:644:5)
[19:29:36] 'deploy' errored after 2.58 s

**Comment by sondr3** [comment]
Seems like a syntax error in one of the dependencies for one of the packages used in the gulpfile, not really sure what it could be and I'm away from my computer for a few months so I can test it sadly. Are you using the regular version of my generator or have you added your own tasks and such?

**Comment by pdkaizer** [comment]
Using your tasks out of the box, have not added any.  Would running an update on the packages help?

**Comment by sondr3** [comment]
Yes, first try to remove all your installed packages and then reinstall and see if it helps. Otherwise I'd run 'npm outdated' and update the outdated packages and then remove 'node_modules' and reinstall them.

**Comment by pdkaizer** [comment]
Removing the node modules and doing a reinstall seemed to do the trick. Thanks!

**Comment by sondr3** [comment]
Awesome, I'll close this issue then. Feel free to reopen or create a new one if needed.
