### ISSUE TITLE
How do you run the beta?

### ISSUE THREAD

**Issue by liquidvisual** [sondr3/generator-jekyllized#90]
Hi there. I'm trying to install the jekyllized generator from the beta branch but I'm getting errors. Not sure if I'm doing it right. I'm trying the following:

    sudo npm install -g https://github.com/sondr3/generator-jekyllized.git@beta

And then it fails:

```shell
npm ERR! fetch failed https://github.com/sondr3/generator-jekyllized.git@beta
npm ERR! Error: 406 Not Acceptable
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1610:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "https://github.com/sondr3/generator-jekyllized.git@beta"
npm ERR! cwd /Users/liquidvisual
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/liquidvisual/npm-debug.log
npm ERR! not ok code 0
```

**Comment by sondr3** [comment]
It should be `sudo npm install -g https://github.com/sondr3/generator-jekyllized.git#beta`. It's a **#** and not a **@**, that should do the trick.

**Comment by liquidvisual** [comment]
Thanks for your reply. Unfortunately I'm still getting an error:

```shell
npm ERR! not a package /tmp/npm-10819-3DEaYRGn/github.com/sondr3/generator-jekyllized.git
npm ERR! Error: ENOENT, open '/tmp/npm-10819-3DEaYRGn/github.com/sondr3/generator-jekyllized.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "https://github.com/sondr3/generator-jekyllized.git#beta"
npm ERR! cwd /Users/liquidvisual/Desktop/yo
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! path /tmp/npm-10819-3DEaYRGn/github.com/sondr3/generator-jekyllized.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/liquidvisual/Desktop/yo/npm-debug.log
npm ERR! not ok code 0
```

**Comment by sondr3** [comment]
Ah, yeah, I've had this problem before. Trying installing it as `sudo npm install -g "https://github.com/sondr3/generator-jekyllized#beta"`. You don't actually need to end the repo with `.git` and for some reason you need to escape the repo URL. See if it works, it worked on my end.

**Comment by liquidvisual** [comment]
Hmm, it's still not recognising it as a package. Strange. I've gone in with sudo and also escaped the repo as your example above. Any ideas of what else I could try? :/

```shell
Sara:~ liquidvisual$ sudo npm install -g "https://github.com/sondr3/generator-jekyllized#beta"
npm ERR! not a package /tmp/npm-11022-01v936A2/github.com/sondr3/generator-jekyllized
npm ERR! Error: ENOENT, open '/tmp/npm-11022-01v936A2/github.com/sondr3/generator-jekyllized-unpack/package.json'
```

**Comment by sondr3** [comment]
Strange, what version of Node and NPM are you using?

**Comment by liquidvisual** [comment]
npm 1.4.28
node 0.10.34

I'll try updating and report back

**Comment by sondr3** [comment]
Oh yeah, you're using pretty old versions. I have NPM 2.11.1 and Node 0.12.5, try updating them and see how that works :)

**Comment by liquidvisual** [comment]
Updating seemed to do the trick - although I had a few heart attacks as it broke a bunch of other stuff. I was able to install the generator without any errors - but now when running "yo generator-jekyllized" it throws an error before completing. :/

It's all so confusing,

```shell
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:4586
        throw e;
              ^
TypeError: undefined is not a function
    at run (/usr/local/lib/node_modules/generator-jekyllized/node_modules/yeoman-generator/lib/base.js:473:21)
    at composeWith (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/base.js:568:15)
    at yoyo._initGenerator (/usr/local/lib/node_modules/yo/yoyo.js:100:8)
    at null.<anonymous> (/usr/local/lib/node_modules/yo/yoyo.js:407:35)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1929:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:4604:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
    at AnonymousObserver._onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:3073:49)
Sara:yo liquidvisual$ 
```

**Comment by liquidvisual** [comment]
Scratch that, I managed to get it working - I just had to update Yeoman first! :)

Thanks for your help :D

**Comment by sondr3** [comment]
What is the error Gulp gives? You have to install `gulp-cli` from Github under the `4.0` branch globally and then install the packages for the project itself.

**Comment by liquidvisual** [comment]
Alrighty, no errors anymore - had to npm install babel-core to get it to work though.

Running gulp fires up the browser, but nothing is served. "Cannot GET /" - should it be displaying anything?

**Comment by sondr3** [comment]
Uh, yeah, it should display the website. Is the `dist` directory empty? Because when you run `gulp` it should generate the Jekyll site.

**Comment by liquidvisual** [comment]
It doesn't seem to generate the ```dist``` directory, no

**Comment by liquidvisual** [comment]
Ah, there was an error:

```
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
```

**Comment by liquidvisual** [comment]
This is my full output, it does say it's serving from ```dist``` at the bottom though. Do I need to do anything else?

```
Sara:crow liquidvisual$ gulp
[03:48:28] Requiring external module babel-core/register
[03:48:29] Using gulpfile ~/Desktop/crow/gulpfile.babel.js
[03:48:29] Starting 'default'...
[03:48:29] Starting 'series'...
[03:48:29] Starting 'jekyll:dev'...
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
[03:48:30] Finished 'jekyll:dev' after 1.22 s
[03:48:30] Finished 'series' after 1.23 s
[03:48:30] Starting 'parallel'...
[03:48:30] Starting 'styles'...
[03:48:30] Starting 'javascript'...
[03:48:30] Starting 'fonts'...
[03:48:30] Starting 'images'...
[03:48:31] Finished 'fonts' after 718 ms
[03:48:31] 'styles' all files 24.97 kB
[03:48:31] Finished 'styles' after 846 ms
[03:48:31] 'images' all files 539 B
[03:48:31] Finished 'images' after 846 ms
[03:48:31] 'javascript' all files 284 B
[03:48:31] Finished 'javascript' after 847 ms
[03:48:31] Finished 'parallel' after 848 ms
[03:48:31] Starting 'series'...
[03:48:31] Starting 'serve'...
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.76:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.76:3001
 -------------------------------------
[BS] Serving files from: dist
[BS] Serving files from: .tmp
```

**Comment by sondr3** [comment]
Ah, yeah, there's a problem with the Gemfile this time around, haha. Can you show me your Gemfile? Or just remove the `Gemfile.lock` and reinstalling them because it's using the old version of Jekyll instead of the new 3.0 beta.

**Comment by liquidvisual** [comment]
I removed Gemfile.lock and re-ran NPM - still get the same error.

Maybe it's better if I just wait for it to come out of beta, this might be a bit over my head.

Here is the gemfile:

```
source "http://rubygems.org"

gem 'jekyll', '~> 3.0.0.pre.beta8'
gem 'redcarpet'
gem 'classifier-reborn'

# jekyll plugins
gem 'jekyll-archives', :git => 'https://github.com/jekyll/jekyll-archives'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'jekyll-feed'
gem 'jekyll-gist'

# octopress
gem 'octopress', '~> 3.0'
```

**Comment by sondr3** [comment]
Oh, it's not NPM, it's the Ruby gems, hah. Remove the `Gemfile.lock` and run `bundle install` and then running `gulp` should work fine.

**Comment by liquidvisual** [comment]
Didn't seem to work :(

**Comment by sondr3** [comment]
Strange, what happens when you run `gulp jekyll:dev`?

**Comment by liquidvisual** [comment]
Wait, success! The browser was firing up at localhost:3000 - I changed this to port 3001 and it revealed itself!

**Comment by sondr3** [comment]
Oh, strange, you might have a gulp task running in the background then or something, haven't run into this before myself. Regardless, nice to know it works!

**Comment by liquidvisual** [comment]
What I'm seeing is a webpage for browsersync though - is that right?

Realised it's not creating a ```dist``` folder still.

```gulp jekyll:dev``` :

```shell
^CSara:crow liquidvisual$ gulp jekyll:dev
[04:23:59] Requiring external module babel-core/register
[04:24:00] Using gulpfile ~/Desktop/crow/gulpfile.babel.js
[04:24:00] Starting 'jekyll:dev'...
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
[04:24:01] Finished 'jekyll:dev' after 1.2 s
```

**Comment by sondr3** [comment]
Hah, yep, you still have the wrong version of Jekyll installed. You might have some Gem conflicts around, try running `bundle clean --force`, delete the `Gemfile.lock` and then `bundle`.

**Comment by liquidvisual** [comment]
I'm not currently running the Jekyll beta, I'm on the last stable build. I thought the Gemfile would install Jekyll (what ever version) as an instance in the directory - or is that not right?

**Comment by sondr3** [comment]
You have to use the most recent beta version of Jekyll with the beta branch, otherwise you'll have Gem conflicts and settings that won't work. I thought so too, but it depends on how you set up your Ruby and such, so it's hard to tell.

**Comment by liquidvisual** [comment]
Ah okay, gotcha. I might wait until it comes out of Beta before going forward with it. Thanks again for your help.

**Comment by sondr3** [comment]
Alright, yeah, I'm pretty much just waiting for both Gulp 4.0 and Jekyll 3.0 to be released and then I'm merging the beta branch into master again :)
