### ISSUE TITLE
Is there a way to use regular git commands with this framework?

### ISSUE THREAD

**Issue by antonioOrtiz** [sondr3/generator-jekyllized#92]
Question: I updated a file on my actual repository https://github.com/antonioOrtiz/antonioortiz.github.io while at work, this has caused (naturally) for my repo's to be out of sink with my files at home (locally). I haven't figured out how to roll back on a physical repo (yet). 

This is the error I am getting from my `gulpfile.js`

     [20:50:06] Using gulpfile ~/Sites/antonioortiz.github.io/gulpfile.js
     [20:50:06] Starting 'deploy'...
     [20:50:06] [gulp-master]: Cloning repo
     [20:50:06] [gulp-master]: Checkout branch `master`
     [20:50:06] [gulp-master]: Copying files to repository
     [20:50:07] [gulp-master]: Adding 13 files.
     [20:50:07] [gulp-master]: Commiting "Update 2015-07-22T00:50:06.484Z"
     [20:50:07] [gulp-master]: Pushing to remote.

      /Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
       Error: Error: Command failed: To https://github.com/antonioOrtiz/antonioortiz.github.io.git
        ! [rejected]        master -> master (fetch first)
       error: failed to push some refs to 'https://github.com/antonioOrtiz/antonioortiz.github.io.git'
       hint: Updates were rejected because the remote contains work that you do
       hint: not have locally. This is usually caused by another repository pushing
       hint: to the same ref. You may want to first integrate the remote changes
       hint: (e.g., 'git pull ...') before pushing again.
       hint: See the 'Note about fast-forwards' in 'git push --help' for details.

    at /Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/index.js:143:10
    at tryCatchReject (/Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/antonioortiz/Sites/antonioortiz.github.io/node_modules/gulp-gh-pages/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:419:13)

Have you run into this dilemma? Any help would be appreciated!!!!

**Comment by sondr3** [comment]
So far add I can see the problem is that your local branch is different from the remote branch and therefore refuses to push a new commit to your remote. Not really sure how to fix as it's a git problem.

**Comment by antonioOrtiz** [comment]
Doing 'git branch -dr origin master' worked for me.
